---
:section_name: 소식
:page_number: 2
:pillar_width:
- 2
- 2
- 2
:page_heading_margin_in_lines: 3
:pillar_map:
- - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_02/1_1"
  - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_02/1_2"
  - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_02/1_3"
- - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_02/2_1"
  - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_02/2_2"
  - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_02/2_3"
- - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_02/3_1"
  - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_02/3_2"
  - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_02/3_3"
:ad_type: 5단통
:advertiser: kdb.png
:draw_divider:
