---
:section_name: 1면
:page_number: 1
:pillar_width:
- 4
- 2
:page_heading_margin_in_lines: 10
:pillar_map:
- - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_01/1_1"
  - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_01/1_2"
- - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_01/2_1"
  - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_01/2_2"
  - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_01/2_3"
  - "/Users/mskim/test_data/news_processor/publication/2022-11-30/page_01/2_4"
:ad_type: 5단통
:advertiser: kdb.png
:draw_divider:
