---
:section_name: 소식
:page_number: 2
:pillar_width:
- 2
- 2
- 2
:page_heading_margin_in_lines: 3
:pillar_map:
- - "/usr/src/app/working/2023-01-01/page_02/1_1"
  - "/usr/src/app/working/2023-01-01/page_02/1_2"
  - "/usr/src/app/working/2023-01-01/page_02/1_3"
- - "/usr/src/app/working/2023-01-01/page_02/2_1"
  - "/usr/src/app/working/2023-01-01/page_02/2_2"
  - "/usr/src/app/working/2023-01-01/page_02/2_3"
- - "/usr/src/app/working/2023-01-01/page_02/3_1"
  - "/usr/src/app/working/2023-01-01/page_02/3_2"
  - "/usr/src/app/working/2023-01-01/page_02/3_3"
:ad_type: 5단통
:advertiser: kdb.png
:draw_divider: 
